include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/generated/**"
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    must_be_immutable: error
  plugins:
    - dart_code_metrics

linter:
  rules:
    # Enforced
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_dynamic_calls: true
    sort_pub_dependencies: false

    # Relaxed for productivity
    public_member_api_docs: false
    lines_longer_than_80_chars: false